### ISSUE TITLE
Research live stream

### ISSUE THREAD

**Issue by katieclauswell** [katiechurchwell/portfolio#6]
Integrate live webcam player: https://api.windy.com/webcams/docs#query-parameter

**Comment by katiechurchwell** [comment]
and ASCII filter overlay?

**Comment by katieclauswell** [comment]
caman.js https://www.youtube.com/watch?v=MEENB3_9yUw

**Comment by katiechurchwell** [comment]
idea: random image, api to make background transparent, ASCII filter and CSS animation to make it float up and down a little?

**Comment by katieclauswell** [comment]
dithering: https://ditherit.com/
https://github.com/leeoniya/RgbQuant.js

**Comment by katiechurchwell** [comment]
Pixelating doesn't work

**Comment by katiechurchwell** [comment]
remove Smith Rock from rotation.
